// Original 10 icons with burst and trail
export { BellIcon } from "./icons/BellIcon"
export { HeartIcon } from "./icons/HeartIcon"
export { StarIcon } from "./icons/StarIcon"
export { TrashIcon } from "./icons/TrashIcon"
export { SearchIcon } from "./icons/SearchIcon"
export { SunMoonIcon } from "./icons/SunMoonIcon"
export { DownloadIcon } from "./icons/DownloadIcon"
export { SendIcon } from "./icons/SendIcon"
export { LoaderIcon } from "./icons/LoaderIcon"
export { BookmarkIcon } from "./icons/BookmarkIcon"

// Navigation (10)
export { HomeIcon } from "./icons/HomeIcon"
export { MenuIcon } from "./icons/MenuIcon"
export { ArrowLeftIcon } from "./icons/ArrowLeftIcon"
export { ArrowRightIcon } from "./icons/ArrowRightIcon"
export { ArrowUpIcon } from "./icons/ArrowUpIcon"
export { ArrowDownIcon } from "./icons/ArrowDownIcon"
export { ChevronDownIcon } from "./icons/ChevronDownIcon"
export { ChevronRightIcon } from "./icons/ChevronRightIcon"
export { ExternalLinkIcon } from "./icons/ExternalLinkIcon"
export { MoreHorizontalIcon } from "./icons/MoreHorizontalIcon"

// User & Auth (10)
export { UserIcon } from "./icons/UserIcon"
export { UsersIcon } from "./icons/UsersIcon"
export { LockIcon } from "./icons/LockIcon"
export { UnlockIcon } from "./icons/UnlockIcon"
export { EyeIcon } from "./icons/EyeIcon"
export { EyeOffIcon } from "./icons/EyeOffIcon"
export { LogInIcon } from "./icons/LogInIcon"
export { LogOutIcon } from "./icons/LogOutIcon"
export { ShieldIcon } from "./icons/ShieldIcon"
export { KeyIcon } from "./icons/KeyIcon"

// Communication (10)
export { MailIcon } from "./icons/MailIcon"
export { MessageSquareIcon } from "./icons/MessageSquareIcon"
export { MessageCircleIcon } from "./icons/MessageCircleIcon"
export { PhoneIcon } from "./icons/PhoneIcon"
export { VideoIcon } from "./icons/VideoIcon"
export { MicIcon } from "./icons/MicIcon"
export { MicOffIcon } from "./icons/MicOffIcon"
export { ShareIcon } from "./icons/ShareIcon"
export { LinkIcon } from "./icons/LinkIcon"
export { AtSignIcon } from "./icons/AtSignIcon"

// Files (10)
export { FileIcon } from "./icons/FileIcon"
export { FileTextIcon } from "./icons/FileTextIcon"
export { FolderIcon } from "./icons/FolderIcon"
export { UploadIcon } from "./icons/UploadIcon"
export { ImageIcon } from "./icons/ImageIcon"
export { PaperclipIcon } from "./icons/PaperclipIcon"
export { CopyIcon } from "./icons/CopyIcon"
export { ClipboardIcon } from "./icons/ClipboardIcon"
export { DatabaseIcon } from "./icons/DatabaseIcon"
export { HardDriveIcon } from "./icons/HardDriveIcon"

// Actions (10)
export { PlusIcon } from "./icons/PlusIcon"
export { MinusIcon } from "./icons/MinusIcon"
export { CloseIcon } from "./icons/CloseIcon"
export { CheckIcon } from "./icons/CheckIcon"
export { EditIcon } from "./icons/EditIcon"
export { RefreshIcon } from "./icons/RefreshIcon"
export { FilterIcon } from "./icons/FilterIcon"
export { SortIcon } from "./icons/SortIcon"
export { ZoomInIcon } from "./icons/ZoomInIcon"
export { ZoomOutIcon } from "./icons/ZoomOutIcon"

// Media (10)
export { PlayIcon } from "./icons/PlayIcon"
export { PauseIcon } from "./icons/PauseIcon"
export { StopIcon } from "./icons/StopIcon"
export { SkipForwardIcon } from "./icons/SkipForwardIcon"
export { SkipBackIcon } from "./icons/SkipBackIcon"
export { VolumeIcon } from "./icons/VolumeIcon"
export { VolumeOffIcon } from "./icons/VolumeOffIcon"
export { MusicIcon } from "./icons/MusicIcon"
export { CameraIcon } from "./icons/CameraIcon"
export { CastIcon } from "./icons/CastIcon"

// E-Commerce (10)
export { ShoppingCartIcon } from "./icons/ShoppingCartIcon"
export { ShoppingBagIcon } from "./icons/ShoppingBagIcon"
export { CreditCardIcon } from "./icons/CreditCardIcon"
export { PackageIcon } from "./icons/PackageIcon"
export { TagIcon } from "./icons/TagIcon"
export { GiftIcon } from "./icons/GiftIcon"
export { PercentIcon } from "./icons/PercentIcon"
export { WalletIcon } from "./icons/WalletIcon"
export { BarChartIcon } from "./icons/BarChartIcon"
export { TrendingUpIcon } from "./icons/TrendingUpIcon"

// System (10)
export { SettingsIcon } from "./icons/SettingsIcon"
export { SlidersIcon } from "./icons/SlidersIcon"
export { ToggleIcon } from "./icons/ToggleIcon"
export { InfoIcon } from "./icons/InfoIcon"
export { AlertCircleIcon } from "./icons/AlertCircleIcon"
export { HelpCircleIcon } from "./icons/HelpCircleIcon"
export { TerminalIcon } from "./icons/TerminalIcon"
export { CodeIcon } from "./icons/CodeIcon"
export { GlobeIcon } from "./icons/GlobeIcon"
export { WifiIcon } from "./icons/WifiIcon"

// Social (10)
export { ThumbsUpIcon } from "./icons/ThumbsUpIcon"
export { ThumbsDownIcon } from "./icons/ThumbsDownIcon"
export { FlagIcon } from "./icons/FlagIcon"
export { AwardIcon } from "./icons/AwardIcon"
export { TrophyIcon } from "./icons/TrophyIcon"
export { ZapIcon } from "./icons/ZapIcon"
export { FlameIcon } from "./icons/FlameIcon"
export { CrownIcon } from "./icons/CrownIcon"
export { SmileIcon } from "./icons/SmileIcon"
export { FrownIcon } from "./icons/FrownIcon"

// Misc (10)
export { MapPinIcon } from "./icons/MapPinIcon"
export { CalendarIcon } from "./icons/CalendarIcon"
export { ClockIcon } from "./icons/ClockIcon"
export { TimerIcon } from "./icons/TimerIcon"
export { MoonIcon } from "./icons/MoonIcon"
export { CloudIcon } from "./icons/CloudIcon"
export { MapIcon } from "./icons/MapIcon"
export { BatteryIcon } from "./icons/BatteryIcon"
export { PowerIcon } from "./icons/PowerIcon"
export { CpuIcon } from "./icons/CpuIcon"

// Utilities
export { IconCopies } from "./icons/IconCopies"
export type { IconProps, MotionVariant } from "./icons/types"
